---
title: "Blog Post 1"
description: "First Blog Post "
author: "Sarah Yandell"
date: "9/05/25"
categories:
  - reflection
draft: false
---
<!-- In addition to the labs and projects, you will also write short (2-3 paragraph) reflections each week as a way of helping you to catalog your growth in the class. These informal reflections are designed to be published as blog posts on your portfolio website. 
Blog Reflection Ideas
The blog on your Quarto portfolio is a space for you to write weekly reflections on what you’re learning in MicroPs. The list below is a non-exhaustive list of ideas of things you could write about if you’re struggling to come up with ideas.

What is something interesting you learned recently in lab or lecture?
How do you feel like the course is helping you to grow as a person? Reflect on the character traits you listed at the beginning of the course for ideas about specific areas of growth to reflect on.
What did you think about a recent AI prototype? How did your use of AI shape your thinking about what role these tools might play in the future of digital hardware design?
Search the Internet for a recent article related to embedded systems. Reflect on those systems through the lens of what you’re learning in MicroPs.
What are some ideas you’re thinking about exploring in your project and why? -->

Something interesting I learned in the lab was how to solder. I had done it once before in E79 while building the robot, but we did not do very much of it. It was really cool to assemble the board on my own, and I learned more about how soldering works and how connections are made. I also got some more practice with verilog and circuits. While I was introduced to this in E85, I did not feel very confident while doing it at the time. Being able to revisit and putting more time in help build my confidence in being able to build a circuit and program a FPGA to do tasks. 

In regards to AI, I think that AI is very powerful, and when used right, it can be incredibly helpful. I have noticed that for Verilog and cirucit design AI seem to be less accurte, but it is not completely wrong. I personally think that AI does a good job at explaning things and is often correct in that scenario. I think that if you can work along side AI whild understanding what is happening, AI can be very useful in digital hardware design. I think that you have to keep in mind that AI sometimes lies and it is most important to learn and understand.